[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/signup"
  to = "/.netlify/functions/signup"
  status = 200

[[redirects]]
  from = "/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/transaction"
  to = "/.netlify/functions/add-transaction"
  status = 200

[[redirects]]
  from = "/transactions"
  to = "/.netlify/functions/get-transactions"
  status = 200

[[redirects]]
  from = "/archive"
  to = "/.netlify/functions/archive"
  status = 200